### ISSUE TITLE
FullContact::NotFound throwing error not proper status

### ISSUE THREAD

**Issue by amanelis** [fullcontact/fullcontact-api-ruby#7]
When I submit an email that "claims" to return a 404 I end up getting an error. I don't think I should have to catch this as an error right?

```
1.9.2p320 :008 > person = FullContact.person(email: 'crapemail@doodle.com')FullContact::NotFound: GET https://api.fullcontact.com/v2/person.json?email=crapemail%40doodle.com&apiKey=13c50288e1c1a556: 404
from /Users/amanelis/.rvm/gems/ruby-1.9.2-p320@milkshake/gems/fullcontact-0.4.1/lib/faraday/response/fullcontact_errors.rb:12:in `on_complete'
from /Users/amanelis/.rvm/gems/ruby-1.9.2-p320@milkshake/gems/faraday-0.8.1/lib/faraday/response.rb:9:in `block in call'
from /Users/amanelis/.rvm/gems/ruby-1.9.2-p320@milkshake/gems/faraday-0.8.1/lib/faraday/response.rb:63:in `on_complete'
from /Users/amanelis/.rvm/gems/ruby-1.9.2-p320@milkshake/gems/faraday-0.8.1/lib/faraday/response.rb:8:in `call'
from /Users/amanelis/.rvm/gems/ruby-1.9.2-p320@milkshake/gems/faraday_middleware-0.8.8/lib/faraday_middleware/response_middleware.rb:30:in `call'
from /Users/amanelis/.rvm/gems/ruby-1.9.2-p320@milkshake/gems/faraday-0.8.1/lib/faraday/response.rb:8:in `call'
from /Users/amanelis/.rvm/gems/ruby-1.9.2-p320@milkshake/gems/faraday-0.8.1/lib/faraday/request/url_encoded.rb:14:in `call'
from /Users/amanelis/.rvm/gems/ruby-1.9.2-p320@milkshake/gems/faraday-0.8.1/lib/faraday/connection.rb:226:in `run_request'
from /Users/amanelis/.rvm/gems/ruby-1.9.2-p320@milkshake/gems/faraday-0.8.1/lib/faraday/connection.rb:87:in `get'
from /Users/amanelis/.rvm/gems/ruby-1.9.2-p320@milkshake/gems/fullcontact-0.4.1/lib/fullcontact/request.rb:15:in `request'
from /Users/amanelis/.rvm/gems/ruby-1.9.2-p320@milkshake/gems/fullcontact-0.4.1/lib/fullcontact/request.rb:6:in `get'
from /Users/amanelis/.rvm/gems/ruby-1.9.2-p320@milkshake/gems/fullcontact-0.4.1/lib/fullcontact/client/person.rb:11:in `person'
from /Users/amanelis/.rvm/gems/ruby-1.9.2-p320@milkshake/gems/fullcontact-0.4.1/lib/fullcontact.rb:21:in `method_missing'
from (irb):8
from /Users/amanelis/.rvm/gems/ruby-1.9.2-p320@milkshake/gems/railties-3.2.6/lib/rails/commands/console.rb:47:in `start'
from /Users/amanelis/.rvm/gems/ruby-1.9.2-p320@milkshake/gems/railties-3.2.6/lib/rails/commands/console.rb:8:in `start'
from /Users/amanelis/.rvm/gems/ruby-1.9.2-p320@milkshake/gems/railties-3.2.6/lib/rails/commands.rb:41:in `<top (required)>'
from script/rails:6:in `require'
from script/rails:6:in `<main>'1.9.2p320 :009 > person

=> #<Hashie::Rash message="Queued for search. Please retry your query in 5 minutes!" status=202>
```

Then when I try to access the object I get do not get a 404 on the status.

```
1.9.2p320 :011 > person
=> #<Hashie::Rash message="Queued for search. Please retry your query in 5 minutes!" status=202> 
```

Am I crazy or this is kind not making sense?

**Comment by Jeechu** [comment]
@Xorlev how do I use the response for 404? I still get an error like this:
```
person = FullContact.person(phone:9999999999)
FullContact::NotFound: GET https://api.fullcontact.com/v2/person.json?apiKey=xxxxxxxxxxxxxxxx&phone=9999999999: 404
	from /Users/jeechudeka/workspace/simpl/fullcontact/vendor/bundle/ruby/2.2.0/gems/fullcontact-0.13.0/lib/faraday/response/fullcontact_errors.rb:12:in `on_complete'
	from /Users/jeechudeka/workspace/simpl/fullcontact/vendor/bundle/ruby/2.2.0/gems/faraday-0.9.2/lib/faraday/response.rb:9:in `block in call'
	from /Users/jeechudeka/workspace/simpl/fullcontact/vendor/bundle/ruby/2.2.0/gems/faraday-0.9.2/lib/faraday/response.rb:57:in `on_complete'
	from /Users/jeechudeka/workspace/simpl/fullcontact/vendor/bundle/ruby/2.2.0/gems/faraday-0.9.2/lib/faraday/response.rb:8:in `call'
	from /Users/jeechudeka/workspace/simpl/fullcontact/vendor/bundle/ruby/2.2.0/gems/faraday_middleware-0.10.0/lib/faraday_middleware/response_middleware.rb:30:in `call'
```

**Comment by ChaosFreak** [comment]
This still appears to be broken. Using `rescue` isn't optimal since there's no way to tell what kind of error occurred. I'm assuming FullContact.person can fail for reasons other than a 404. Are there any plans to fix this to provide a proper error response?

**Comment by shaneardell** [comment]
Looks like there hasn't been movement on this. Is this still in the pipeline?

**Comment by amanelis** [comment]
I opened this like 5 years ago, closing...
